[build]
builder = "NIXPACKS"
buildCommand = "npm run build && npx playwright install chromium --with-deps"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"

[nixpacks]
# Ensure all system deps for Playwright are available
features = ["chromium"]